# Generated by Django 5.1.6 on 2025-02-28 08:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img'), upload_to=''),
        ),
    ]
