# Generated by Django 5.1.6 on 2025-03-03 17:42

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_alter_hackathon_image'),
        ('user', '0003_user_level_user_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='start_date',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='anonce_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='end_hackathon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='end_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='number_of_winners',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(related_name='hackathons', to='user.user'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='prize_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='start_hackathon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='start_registation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('anonce', 'Анонс'), ('start_registration', 'Регистрации'), ('end_registration', 'Регистрация завершена'), ('started', 'Проводится'), ('determining_stage', 'Определение победителей'), ('finished', 'Завершенный')], default='anonce', max_length=100),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/hackathon_img', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img/hackathon_img'), upload_to=''),
        ),
        migrations.CreateModel(
            name='PrizePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prize_amount', models.IntegerField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_places', to='hackathon.hackathon')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'ordering': ['place'],
                'unique_together': {('hackathon', 'place')},
            },
        ),
    ]
