# Generated by Django 5.1.6 on 2025-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_remove_hackathon_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='type',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('hybrid', 'Гибридный')], default='online', max_length=100),
        ),
    ]
