# Generated by Django 5.1.6 on 2025-03-03 18:54

import django.core.files.storage
import hackathon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_hackathon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hackathon',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/hackathon_img', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img/hackathon_img'), upload_to=hackathon.models.hackathon_image_path),
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='tags',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='hackathons', to='hackathon.tag'),
        ),
    ]
