# Generated by Django 5.1.6 on 2025-03-04 19:44

import django.core.files.storage
import hackathon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0005_tag_hackathon_participants_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/static/img/hackathon_img",
                    location="D:\\hackathonplatform\\core\\static\\img\\hackathon_img",
                ),
                upload_to=hackathon.models.hackathon_image_path,
            ),
        ),
    ]
