# Generated by Django 5.1.6 on 2025-02-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_hash_code_user_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='user.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user.user')),
                ('user3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user3', to='user.user')),
                ('user4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user4', to='user.user')),
            ],
        ),
    ]
