# Generated by Django 5.1.6 on 2025-03-03 17:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/product_img', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img/product_img'), upload_to='product_images/'),
        ),
    ]
