# Generated by Django 5.1.6 on 2025-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_productcategory_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
