# Generated by Django 5.1.6 on 2025-02-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casecup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to='casecup_images/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.category')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to='webinar_images/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.category')),
            ],
        ),
    ]
