# Generated by Django 5.1.6 on 2025-02-28 10:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/post_img', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img/post_img'), upload_to=''),
        ),
    ]
