# Generated by Django 5.1.6 on 2025-03-03 18:49

import django.core.files.storage
import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecup',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/casecup_img', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img/casecup_img'), upload_to=feed.models.casecup_image_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=feed.models.event_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/post_img', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img/post_img'), upload_to=feed.models.post_image_path),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/img/webinar_img', location='/Users/erkebulanmyrzabek/Desktop/HackPlatform/core/static/img/webinar_img'), upload_to=feed.models.webinar_image_path),
        ),
    ]
