# Generated by Django 5.1.6 on 2025-03-03 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_casecup_image_alter_event_image_and_more'),
        ('user', '0003_user_level_user_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='end_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webinar',
            name='max_participants',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='webinar',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='webinars', to='user.user'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='start_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
